name: Builds the project

on: [ push ]

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'License check with Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
        with:
          arguments: checkLicenses
  build:
    needs: license-check
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5.0.0
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Grant Permission to Gradle'
        run: chmod +x gradlew
      - name: 'Build with Gradle'
        uses: gradle/actions/setup-gradle@v4.4.3
        with:
          arguments: build
